services:
  churchgroupbot:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    cap_add:
      - CAP_PERFMON
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6144M
        reservations:
          cpus: '0.5'
          memory: 2048M
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${WORK_DIR}/data/whisper:/.cache/whisper
      - ${WORK_DIR}/data/whisper:/root/.cache/whisper
      - ${WORK_DIR}/app:/app:ro # Optional: If you want to mount the app folder to edit the code without rebuilding the image. DEBUG ONLY
      - ${WORK_DIR}/data/bot.db:/data/bot.db
      - type: tmpfs # Optional: 100MB of memory, reduces SSD/SD Card wear. Here will be stored only the current processed audio file.
        target: /tmp/cache
        tmpfs:
          size: 100000000
    environment:
      - TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
