services:
  churchgroupbot:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${WORK_DIR}/app:/app:ro # Optional: If you want to mount the app folder to edit the code without rebuilding the image. DEBUG ONLY
      - ${WORK_DIR}/data:/data
      - type: tmpfs # Optional: 100MB of memory, reduces SSD/SD Card wear. Here will be stored only the current processed audio file.
        target: /tmp/cache
        tmpfs:
          size: 100000000
    environment:
      - TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
      - WHISPER_SERVICE_HOST=${WHISPER_SERVICE_HOST}
      - WHISPER_SERVICE_PORT=${WHISPER_SERVICE_PORT}
      - WHISPER_SERVICE_URI=${WHISPER_SERVICE_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - TRANSCRIPTION_IMPROVER_MODEL=${TRANSCRIPTION_IMPROVER_MODEL:-gpt-oss:20b}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
